name: Clang

on:
  push:
    branches-ignore:
    - build
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Install latest Clang and libc++
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main" >> /etc/apt/sources.list'
          sudo apt update
          sudo apt-get install -y clang-21 libc++-21-dev libc++abi-21-dev libunwind-21-dev python3-sphinx
          # Install a Ninja version with module support. The one shipped with Ubuntu 22.04 is too old.
          set -e
          wget -qO /tmp/ninja.gz https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
          gunzip /tmp/ninja.gz
          chmod a+x /tmp/ninja
          sudo mv /tmp/ninja /usr/local/bin/ninja
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=clang++-21 -DLLVM_COV_PATH=/usr/bin/llvm-cov-21 -DLLVM_PROFDATA_PATH=/usr/bin/llvm-profdata-21 -DCODE_COVERAGE=ON -GNinja ..
          ninja -v
          ninja ccov-export-tests
          # TODO investigate
          # ../utils/check_coverage.py
          ninja ccov-tests

      - name: Documentation
        run: |
          # These directories are required by Sphinx but since they are empty they're not in git.
          mkdir doc/_static
          mkdir doc/_templates
          sphinx-build -b html doc www
          cp -r build/ccov/tests www/coverage

      - name: Update website
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: www
          FOLDER: www
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Publish: ({sha})"
