name: Clang

on:
  push:
    branches-ignore:
    - build
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Install latest Clang and libc++
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main" >> /etc/apt/sources.list'
          sudo apt update
          sudo apt-get install -y clang-17 libc++-17-dev libc++abi-17-dev libunwind-17-dev python3-sphinx
          # Ninja 1.11 is needed to use modules in CMake. This version is not
          # available in Ubuntu 22.04. Therefore install it manually.
          sudo wget -qO /usr/local/bin/ninja.gz https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip
          sudo gunzip /usr/local/bin/ninja.gz
          sudo chmod a+x /usr/local/bin/ninja
          # CMake 3.26 is needed to use modules. This version is not available
          # yet so manually install a RC version.
          sudo apt-get remove -y cmake
          wget https://github.com/Kitware/CMake/releases/download/v3.26.0-rc5/cmake-3.26.0-rc5-linux-x86_64.sh -O /tmp/install-cmake.sh
          sudo bash /tmp/install-cmake.sh --prefix=/usr --exclude-subdir --skip-license
      - name: Build
        run: |
          mkdir build
          cd build
          # The full path to the CXX compiler is needed when using modules.
          # clang-scan-deps does not work properly with a symlink.
          cmake -DCMAKE_CXX_COMPILER=/usr/lib/llvm-17/bin/clang++ -DLLVM_COV_PATH=/usr/bin/llvm-cov-17 -DLLVM_PROFDATA_PATH=/usr/bin/llvm-profdata-17 -DCODE_COVERAGE=ON -GNinja ..
          # The dependency information is not entirely correct, this leads to
          # build failures when running jobs in parallel.
          ninja -j1 -v
          ninja -j1 ccov-export-tests
          ../utils/check_coverage.py
          ninja -j1 ccov-tests

      - name: Documentation
        run: |
          # These directories are required by Sphinx but since they are empty they're not in git.
          mkdir doc/_static
          mkdir doc/_templates
          sphinx-build -b html doc www
          cp -r build/ccov/tests www/coverage

      - name: Update website
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: www
          FOLDER: www
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Publish: ({sha})"
