name: Clang

on:
  push:
    branches-ignore:
    - build
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest Clang and libc++
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal main" >> /etc/apt/sources.list'
          sudo apt update
          sudo apt-get install -y clang-14 libc++-14-dev libc++abi-14-dev libunwind-14-dev python3-sphinx
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=clang++-14 -DLLVM_COV_PATH=/usr/bin/llvm-cov-14 -DLLVM_PROFDATA_PATH=/usr/bin/llvm-profdata-14 -DCODE_COVERAGE=ON ..
          make VERBOSE=1
          make ccov-export-tests
          ../utils/check_coverage.py
          make ccov-tests

      - name: Documentation
        run: |
          # These directories are required by Sphinx but since they are empty they're not in git.
          mkdir doc/_static
          mkdir doc/_templates
          sphinx-build -b html doc www
          cp -r build/ccov/tests www/coverage

      - name: Update website
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: www
          FOLDER: www
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Publish: ({sha})"
